name: Run Ruff and Pytests

on:
  push:
    branches:
      - '**'

jobs:
  Ruff_and_Pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install package with dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff packaging
          pip install .

      - name: Run Ruff Format
        run: ruff check --fix .

      - name: Run Ruff Check
        run: ruff check .

      - name: Check Package Version
        run: |
          python -c "from importlib.metadata import version; \
          import json, sys, urllib.request, packaging.version; \
          current_version = packaging.version.parse(version('qec')); \
          with urllib.request.urlopen('https://pypi.org/pypi/qec/json') as response: \
              data = json.load(response); \
          latest_version = packaging.version.parse(data['info']['version']); \
          print(f'Current version: {current_version}, Latest version on PyPI: {latest_version}'); \
          if current_version > latest_version: sys.exit(0) \
          else: sys.exit('Current package version must be higher than the version on PyPI.')"

      - name: Run Pytest
        run: pytest