name: Run Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install package with dependencies
        run: |
          python -m pip install --upgrade pip
          # Install the package; pyproject.toml dependencies will be read automatically
          pip install .

      - name: Run Pytest
        run: pytest
